### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Haeretiker**
I build mini-snmpd for my openwrt based router and ran intosome troubles when i tried to use it with mrtg.
At least mrtg is happy now ;-)

### CODE REVIEW

**Comment by troglobit** [comment]
Great stuff!  Do you think you could refactor the commit messages to something like this and force-push an update to this pull-request?  Then I'll merge this gold mine :smiley: :+1: 

    Capitalized, short (50 chars or less) summary
    
    More detailed explanatory text, if necessary.  Wrap it to about 72
    characters or so.  In some contexts, the first line is treated as the
    subject of an email and the rest of the text as the body.  The blank
    line separating the summary from the body is critical (unless you omit
    the body entirely); tools like rebase can get confused if you run the
    two together.
    
    Write your commit message in the imperative: "Fix bug" and not "Fixed bug"
    or "Fixes bug."  This convention matches up with commit messages generated
    by commands like git merge and git revert.
    
    Further paragraphs come after blank lines.
    
    - Bullet points are okay, too
    
    - Typically a hyphen or asterisk is used for the bullet, followed by a
      single space, with blank lines in between, but conventions vary here
    
    - Use a hanging indent
    
    Signed-off-by: Some Namesson <user@example.org>


http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by Haeretiker** [comment]
I'll try this tomorrow

**Comment by troglobit** [comment]
Thanks! :)

**Comment by Haeretiker** [comment]
Done. At least I hope so. I'm new to git - used cvs and svn for ages ;)
There's a minor issue with parse_line (still partial matches possible) I'll address soon
The change to use stroull will cause wraparound for meminfo, too. A possible fix may extending field_t, adding a bool indicating if wraparound or saturation is desired

**Comment by troglobit** [comment]
This looks awesome, thanks! :-)

**Pull request merged**
